
    create table admin (
        role smallint check (role between 0 and 2),
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        primary key (user_id)
    );

    create table class_schedule (
        done boolean not null,
        class_id bigint generated by default as identity,
        course_id bigint not null,
        duration bigint not null,
        student_id bigint not null,
        teacher_id bigint not null,
        course_timing varchar(255),
        primary key (class_id)
    );

    create table course (
        course_id bigint generated by default as identity,
        course_level varchar(255),
        course_name varchar(255),
        curriculum varchar(255),
        primary key (course_id)
    );

    create table enrollment (
        course_id integer not null,
        student_id integer not null,
        teacher_id integer not null,
        enrollment_id bigint generated by default as identity,
        enrollment_date varchar(255),
        primary key (enrollment_id)
    );

    create table student (
        role smallint check (role between 0 and 2),
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        primary key (user_id)
    );

    create table teacher (
        role smallint check (role between 0 and 2),
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        primary key (user_id)
    );

    create table admin (
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        role varchar(255) check (role in ('ADMIN','STUDENT','TEACHER')),
        primary key (user_id)
    );

    create table class_schedule (
        done boolean not null,
        class_id bigint generated by default as identity,
        course_id bigint not null,
        duration bigint not null,
        student_id bigint not null,
        teacher_id bigint not null,
        course_timing varchar(255),
        primary key (class_id)
    );

    create table course (
        course_id bigint generated by default as identity,
        course_level varchar(255),
        course_name varchar(255),
        curriculum varchar(255),
        primary key (course_id)
    );

    create table enrollment (
        course_id integer not null,
        student_id integer not null,
        teacher_id integer not null,
        enrollment_id bigint generated by default as identity,
        enrollment_date varchar(255),
        primary key (enrollment_id)
    );

    create table student (
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        role varchar(255) check (role in ('ADMIN','STUDENT','TEACHER')),
        primary key (user_id)
    );

    create table teacher (
        user_id bigint generated by default as identity,
        email varchar(255) unique,
        google_id varchar(255),
        name varchar(255),
        password varchar(255),
        phone_number varchar(255),
        profile_pic varchar(255),
        role varchar(255) check (role in ('ADMIN','STUDENT','TEACHER')),
        primary key (user_id)
    );
