spring:
  application:
    name: lms

  datasource:
    url: jdbc:postgresql://localhost:5432/lmsdb
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jakarta.persistence.schema-generation.scripts:
        action: create
        create-target: schema.sql
        create-source: metadata
      hibernate:
        format_sql: true

server:
  port: 8082