spring:
  application:
    name: lms
  security.user.name: user
  security.user.password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/lmsdb
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
