CREATE TABLE IF NOT EXISTS student (
    role VARCHAR(50),
    user_id bigint generated by default as identity,
    email varchar(255) unique,
    google_id varchar(255),
    name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    profile_pic varchar(255),
    primary key (user_id)
    );