create table enrollment (
    course_id integer not null,
    student_id integer not null,
    teacher_id integer not null,
    enrollment_id bigint generated by default as identity,
    enrollment_date varchar(255),
    primary key (enrollment_id)
);