create table class_schedule (
    done boolean not null,
    class_id bigint generated by default as identity,
    course_id bigint not null,
    duration bigint not null,
    student_id bigint not null,
    teacher_id bigint not null,
    course_timing varchar(255),
    primary key (class_id)
);